export const suburbs = [
  "Bahrs Scrub",
  "Beenleigh",
  "Bethania",
  "Browns Plains",
  "Burleigh Heads",
  "Carina",
  "Coomera",
  "Crestmead",
  "Daisy Hill",
  "Eagleby",
  "Eight Mile Plains",
  "Helensvale",
  "Hillcrest",
  "Hope Island",
  "Jimboomba",
  "Logan Central",
  "Logan Reserve",
  "Logan Village",
  "Loganholme",
  "Loganlea",
  "Marsden",
  "Meadowbrook",
  "Mount Gravatt",
  "Ormeau",
  "Park Ridge",
  "Pimpama",
  "Redland Bay",
  "Rochedale",
  "Shailer Park",
  "Slacks Creek",
  "South Brisbane",
  "Springwood",
  "Sunnybank",
  "Surfers Paradise",
  "Underwood",
  "Upper Coomera",
  "Waterford",
  "Windaroo",
  "Woolloongabba",
  "Yarrabilba",
] as const;
